name: build_wheels

on:
  workflow_dispatch:
    inputs:
      is_release:
        description: "Set to true if a release version."
        required: true
        default: false
        type: boolean
      sha:
        description: "The git SHA to use for release.  Only set if needing to publish"
        required: false
        default: ""
        type: string
      version:
        description: "The Release version.  Allowed format: x.y.z[-alphaN | -betaN | -rcN | -devN | -postN]"
        required: false
        default: ""
        type: string
      cxx_change:
        description: "The PR number or SHA if wanting to build against a PR/SHA in the C++ SDK"
        required: false
        type: string

env:
  DEFAULT_PYTHON: "3.9"
  PYTHON_VERSIONS: "3.9,3.10,3.11,3.12,3.13"
  X86_64_PLATFORMS: "manylinux2014,musllinux_1_1,macosx,win"
  ARM64_PLATFORMS: "manylinux2014,macosx"
  CI_SCRIPTS_URL: "https://raw.githubusercontent.com/thejcfactor/ci_testing/main/ci"

jobs:
  ci-scripts:
    runs-on: ubuntu-22.04
    steps:
      - name: Download CI Scripts
        run: |
          mkdir ci_scripts
          cd ci_scripts
          curl -o gha.sh ${CI_SCRIPTS_URL}/gha.sh
          ls -alh
          cat gha.sh
      - name: Upload CI scripts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: ci_scripts
          path: |
            ci_scripts/

  validate-input:
    runs-on: ubuntu-22.04
    needs: ci-scripts
    env:
      INPUT_IS_RELEASE: ${{ inputs.is_release }}
      INPUT_SHA: ${{ inputs.sha }}
      INPUT_VERSION: ${{ inputs.version }}
      INPUT_CXX_CHANGE: ${{ inputs.cxx_change }}
    steps:
      - name: Download CI scripts
        uses: actions/download-artifact@v4
        with:
          name: ci_scripts
          path: ci_scripts
      - name: Verify Scripts
        run: |
          ls -alh ci_scripts
          chmod +x ci_scripts/gha.sh
          ls -alh ci_scripts
      - name: Display workflow info
        run: |
          ./ci_scripts/gha.sh display_info
      - name: Validate workflow info
        run: |
          ./ci_scripts/gha.sh validate_input ${{ github.workflow }}